name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.20.0'
        cache: true
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Build
      uses: ouzi-dev/go-make-action@v1.5.0
      env:
        GOROOT: ""
      with:
        target: code/compile
    - name: Verify vendor directory
      uses: ouzi-dev/go-make-action@v1.5.0
      env:
        GOROOT: ""
      with:
        target: setup/mod/verify