name: Lint
on: [push, pull_request]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
          cache: true
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Lint
        run: make setup/linter code/lint