name: Release Keycloak Operator container

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write

concurrency: keycloak-operator-container-release

jobs:
  publish:
    if: github.repository == 'dmolik/keycloak-operator'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Container metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/gulfcoastdevops/keycloak-operator
          656688821056.dkr.ecr.us-east-1.amazonaws.com/keycloak-operator
        flavor: |
          latest=false
        tags: |
          type=ref,event=branch
          type=raw,value=legacy
          type=semver,pattern={{version}}-legacy
          type=semver,pattern={{major}}.{{minor}}-legacy
          type=edge

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Login to AWS ECR Dev
      uses: docker/login-action@v2
      with:
        registry: 656688821056.dkr.ecr.us-east-1.amazonaws.com
        username: ${{ secrets.AWS_DEV_KEY_ID }}
        password: ${{ secrets.AWS_DEV_SECRET_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
