name: Release Keycloak Operator container

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  packages: write

concurrency: keycloak-operator-container-release

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    if: github.repository == 'dmolik/keycloak-operator'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Container metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ghcr.io/dmolik/keycloak-operator
        flavor: |
          latest=false
        tags: |
          type=ref,event=branch
          type=raw,value=legacy
          type=semver,pattern={{version}}-legacy
          type=semver,pattern={{major}}.{{minor}}-legacy
          type=edge

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
